### ISSUE TITLE
Are the docs broken?

### ISSUE THREAD

**Issue by aringot** [brightway-lca/brightway-documentation#100]
Hi, I wanted to understand how to use Brightway and feel like the docs are broken.

When I go to https://documentation.brightway.dev/en/latest/index.html the only link that is working is the API reference.

Am I missing something? How do I get to explanations and tutorials? (I did find some Jupyter Notebooks that gave me an idea of how using Brightway IO looks like, but I would like more background on the concepts used)

Thanks!

**Comment by cmutel** [comment]
@michaelweinold I assume you know about this already 😛 

The sections `LCA` and `Gallery` are currently broken. The `learn.brightway.dev` has a certificate problem - is this hosted on our server? I can change the DNS settings as needed, just let me know.

**Comment by michaelweinold** [comment]
Hey, @aringot!

> I feel like the docs are broken.

We are hosting the documentation on readthedocs.org. This morning, the fine folks of their development team helped me resolve an issue that I discovered, which affected all users of their platform (cf. https://github.com/readthedocs/readthedocs.org/issues/10477).
As part of this fix/upgrade, I managed to break a few pages (which you noticed). It's all fixed now - just refresh your browser.

> How do I get to explanations and tutorials?

At this time, you can look through this collection of Jupyter Notebooks that we use for teaching: [`brightway-lca/from-the-ground-up`](https://github.com/brightway-lca/from-the-ground-up/).

In the near future (to be discussed with @cmutel), we'll have a separate repository to collect Brightway examples and tutorials.

> I would like more background on the concepts used

I would recommend this section of the documentation: [LCA](https://documentation.brightway.dev/en/latest/content/lca/index.html)

**Comment by aringot** [comment]
@michaelweinold thanks for the detailed explanation! Fyi, the links on the left side still seem to be broken (e.g. LCA links to [source/lca/index.html](https://documentation.brightway.dev/en/latest/source/lca/index.html) instead of [content/lca/index.html](https://documentation.brightway.dev/en/latest/content/lca/index.html)) and I still get the certificate issue for learn.brightway.dev.

Another thing I noticed is that something weird happened on some headings (might be an old HTML anchor?):
Exchange data format **_{#exchanges}_**
<img width="1010" alt="Screenshot 2023-07-19 at 17 34 28" src="https://github.com/brightway-lca/brightway-documentation/assets/5434864/5668dd1c-dc54-4ff3-abea-3dc515969f7e">

**Comment by michaelweinold** [comment]
> Another thing I noticed

As the page indicates at the very top:

<img width="744" alt="Screenshot 2023-07-19 at 18 38 58" src="https://github.com/brightway-lca/brightway-documentation/assets/23102087/b26ff980-d61a-4e69-ba15-b6f6a2094e9b">

Feel free to open a PR to fix these artefacts - otherwise they won't go away 😎

I have a few broken links on the radar (cf. https://github.com/brightway-lca/brightway-documentation/issues/95). `learn.brightway.dev` is still under construction.

**Comment by tngTUDOR** [comment]
> @michaelweinold I assume you know about this already stuck_out_tongue
> 
> The sections `LCA` and `Gallery` are currently broken. The `learn.brightway.dev` has a certificate problem - is this hosted on our server? I can change the DNS settings as needed, just let me know.

@cmutel  where is this supposed to point to anyway ? I don't see the "site" on either server.

**Comment by tngTUDOR** [comment]
It's getting tricky to find out the exact format required to build the URLs so that readthedocs respects them.

**Comment by michaelweinold** [comment]
> It's getting tricky to find out the exact format required to build the URLs so that readthedocs respects them.

Best to open this in a new issue:

- https://github.com/brightway-lca/brightway-documentation/issues/104

I might need to add some documentation on how to use relative paths to link to other pages.

> @cmutel where is this supposed to point to anyway ? I don't see the "site" on either server

Resolved as per my email to the both of you.

**Comment by tngTUDOR** [comment]
@aringot , with the closing of #104 , the documentation website is fully functional again.
Thank you for reporting the broken docs.
